import {Store} from './src/state/store.js';
import {SimRobot} from './src/robot/sim_robot.js';
import {WarehouseRenderer} from './src/environment/warehouse.js';
import {RulePlanner} from './src/planner/rule_planner.js';
import {Planner} from './src/planner/planner.js';
import {SkillExecutor} from './src/skills/skills.js';
import {RulePolicy} from './src/policy/rule_policy.js';
import {EpisodeLogger} from './src/logging/episode_logger.js';
import {buildObservation,buildAction,buildResult} from './src/core/schemas.js';
import {generateScenarios,applyScenario,taskTextForScenario} from './src/benchmark/scenarios.js';
const $=s=>document.querySelector(s);const store=new Store();const robot=new SimRobot(store);robot.connect();const renderer=new WarehouseRenderer($('#simCanvas'));const planner=new Planner(new RulePlanner());const policy=new RulePolicy(store,robot);const executor=new SkillExecutor(store,policy);const episodes=new EpisodeLogger();let running=false,batchRunning=false,lastBenchmark=null;
function log(type,msg){const d=document.createElement('div');d.className=`log-line ${type}`;const t=new Date().toLocaleTimeString();d.innerHTML=`<span class="time">${t}</span> ${msg}`;$('#log').appendChild(d);$('#log').scrollTop=$('#log').scrollHeight}
function render(s){renderer.draw(s);$('#robotState').textContent=JSON.stringify({robot:s.robot,simulation:s.simulation,path:{active:s.path.active,index:s.path.index,lookaheadTarget:s.path.lookaheadTarget},benchmark:s.benchmark||null},null,2);$('#agentState').textContent=JSON.stringify({task:s.task,agent:s.agent,perception:s.perception,failures:s.failures,obstacle:s.obstacle.enabled},null,2);renderHistory(s);syncControls(s);renderMetrics()}
function renderHistory(s){const q=$('#skillQueue');q.innerHTML='';if(!s.agent.history.length){q.innerHTML='<div class="hint">No decisions yet.</div>';return;}s.agent.history.slice().reverse().forEach((h,i)=>{const e=document.createElement('div');e.className='skill-item '+(i===0?'current':'done');e.innerHTML=`<span>#${h.step} ${h.skill}${h.recovery?' ↻ recovery':''}</span><code>${JSON.stringify(h.result)}</code>`;q.appendChild(e)})}
function syncControls(s){$('#obstacleToggle').checked=s.obstacle.enabled;$('#detectFailToggle').checked=s.failures.forceDetectionFailure;$('#alignFailToggle').checked=s.failures.forceAlignmentFailure;$('#insertFailToggle').checked=s.failures.forceInsertionFailure;$('#controllerSelect').value=s.simulation.controller;$('#lookaheadInput').value=s.simulation.lookaheadDistance}
function renderMetrics(){const ep=episodes.current||episodes.completed.at(-1);$('#episodeState').textContent=ep?JSON.stringify({id:ep.id,status:ep.status||'running',meta:ep.meta,metrics:ep.metrics},null,2):'No episode yet.'}
store.subscribe(render);
async function makePlan(){const text=$('#taskInput').value.trim();if(!text){log('error','Task is empty');return false;}store.state.task=await planner.createTask(text);Object.assign(store.state.agent,{currentSkill:null,lastResult:null,status:store.state.task.status==='invalid'?'invalid':'ready',stepCount:0,history:[]});store.state.agent.memory={retreated:false,alternateRoute:false,retries:{},lastFailedSkill:null};store.state.perception.detectedPallets=[];store.emit();if(store.state.task.status==='invalid'){log('error','Task parse failed. Example: パレットAを出荷エリアへ運んで');return false;}episodes.start(store.state.task,{controller:store.state.simulation.controller,vehicleModel:store.state.simulation.vehicleModel,lookaheadDistance:store.state.simulation.lookaheadDistance,benchmark:store.state.benchmark||null});renderMetrics();log('planner',`Task parsed → ${store.state.task.source} → ${store.state.task.destination}; controller=${store.state.simulation.controller}`);return true;}
function finishEpisode(success,status){const ep=episodes.finish(success,status);renderMetrics();if(ep)log(success?'success':'error',`Episode ${ep.id} → ${status}; steps=${ep.metrics.stepCount}, collisions=${ep.metrics.collisions}, cte=${ep.metrics.meanCrossTrackError??'-'}`)}
async function step(){const s=store.state;if(!s.task.raw||s.task.status==='idle'){const ok=await makePlan();if(!ok)return false;}if(['done','failed','invalid'].includes(s.task.status))return false;const observation=buildObservation(s);const decision=await planner.next(s.task,s);if(decision.type==='done'){s.agent.status='done';s.task.status='done';s.agent.currentSkill=null;store.emit();log('success','Planner → DONE');finishEpisode(true,'done');return false;}if(decision.type==='abort'){s.agent.status='failed';s.task.status='failed';s.agent.lastResult={ok:false,reason:decision.reason};store.emit();log('error',`Planner → ABORT: ${decision.reason}`);finishEpisode(false,'aborted');return false;}const sk=decision.skill;s.agent.currentSkill=sk.name;s.agent.status=decision.recovery?'recovering':'running';s.agent.stepCount++;store.emit();log(decision.recovery?'planner':'skill',`${decision.recovery?'Replan recovery':'Planner'} → ${sk.name}`);const action=buildAction(s.agent.stepCount,sk.name,sk.args);const result=buildResult(await executor.execute(sk));s.agent.lastResult=result;s.agent.history.push({step:s.agent.stepCount,skill:sk.name,args:sk.args,recovery:!!decision.recovery,result});if(result.ok){if(decision.recovery)episodes.recovery();s.agent.status='ready';log('success',`Result → success: ${result.message||''}`)}else{s.agent.status='recovering';s.agent.memory.lastFailedSkill=sk.name;s.agent.memory.retries[sk.name]=(s.agent.memory.retries[sk.name]||0)+1;log('error',`Result → failed: ${result.reason}; Planner will reconsider`)}store.emit();episodes.record(observation,action,result,buildObservation(s));renderMetrics();return true;}
async function run(){if(running||batchRunning)return;running=true;let guard=0;while(running&&guard++<40){const keep=await step();if(!keep||['done','failed','invalid'].includes(store.state.task.status))break;await new Promise(r=>setTimeout(r,350))}if(guard>=40)log('error','Run stopped by 40-step safety guard');running=false}
function initTaskForBatch(taskText){store.state.task=planner.adapter.parseTask(taskText);store.state.agent.currentSkill=null;store.state.agent.lastResult=null;store.state.agent.status=store.state.task.status==='invalid'?'invalid':'ready';store.state.agent.stepCount=0;store.state.agent.history=[];store.state.agent.memory={retreated:false,alternateRoute:false,retries:{},lastFailedSkill:null};store.state.perception.detectedPallets=[]}
async function runBatchTrial(taskText,controller,lookahead,scenario=null){store.reset();store.state.simulation.controller=controller;store.state.simulation.lookaheadDistance=lookahead;store.state.simulation.batchMode=true;if(scenario)applyScenario(store.state,scenario);initTaskForBatch(taskText);if(store.state.task.status==='invalid')return{success:false,invalid:true};let success=false,failures=0,recoveries=0,cte=[];for(let guard=0;guard<40;guard++){const s=store.state,decision=await planner.next(s.task,s);if(decision.type==='done'){success=true;break}if(decision.type==='abort')break;const sk=decision.skill;s.agent.stepCount++;const raw=await executor.execute(sk);const result=buildResult(raw);s.agent.lastResult=result;if(Number.isFinite(raw.meanCrossTrackError))cte.push(raw.meanCrossTrackError);if(result.ok){if(decision.recovery)recoveries++}else{failures++;s.agent.memory.lastFailedSkill=sk.name;s.agent.memory.retries[sk.name]=(s.agent.memory.retries[sk.name]||0)+1}}
const sim=store.state.simulation;return{success,failures,recoveries,pathLength:sim.pathLength,controlTicks:sim.controlTicks,simTimeSec:sim.controlTicks*sim.dt,collisions:sim.collisions,meanCrossTrackError:cte.length?cte.reduce((a,b)=>a+b,0)/cte.length:null,scenarioId:scenario?.id||null}}
const avg=(xs,key)=>{const v=xs.map(x=>x[key]).filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};
function summarize(controller,runs){return{controller,trials:runs.length,successRate:runs.filter(x=>x.success).length/runs.length,collisionRate:runs.filter(x=>x.collisions>0).length/runs.length,avgPathLength:avg(runs,'pathLength'),avgSimTimeSec:avg(runs,'simTimeSec'),avgControlTicks:avg(runs,'controlTicks'),avgCTE:avg(runs,'meanCrossTrackError'),avgFailures:avg(runs,'failures'),avgRecoveries:avg(runs,'recoveries')}}
async function runBatch(){if(batchRunning||running)return;batchRunning=true;$('#batchBtn').disabled=true;const scenariosN=Math.max(1,Math.min(50,Number($('#benchmarkScenarios').value)||8)),seed=$('#benchmarkSeed').value||'42',lookahead=Math.max(20,Math.min(120,Number($('#lookaheadInput').value)||55)),controllers=['pure_pursuit','rule_waypoint'],scenarios=generateScenarios(seed,scenariosN),rows=[],details=[];log('planner',`Benchmark start: seed=${seed}, scenarios=${scenariosN}, controllers=${controllers.length}`);for(const controller of controllers){const runs=[];for(let i=0;i<scenarios.length;i++){const scenario=scenarios[i],task=taskTextForScenario(scenario);const result=await runBatchTrial(task,controller,lookahead,scenario);runs.push(result);details.push({controller,scenario,result});$('#batchState').textContent=`${controller}: ${i+1}/${scenarios.length} — ${scenario.id}`;await new Promise(r=>setTimeout(r,0))}rows.push(summarize(controller,runs))}lastBenchmark={version:'v1.5',seed:String(seed),scenarioCount:scenariosN,lookahead,vehicleModel:store.state.simulation.vehicleModel,generatedAt:new Date().toISOString(),summary:rows,details};$('#batchState').textContent=JSON.stringify(lastBenchmark.summary,null,2);store.reset();store.state.simulation.lookaheadDistance=lookahead;store.emit();log('success','Benchmark complete');$('#batchBtn').disabled=false;batchRunning=false}
function downloadText(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function exportBenchmarkJson(){if(!lastBenchmark){log('error','No benchmark result');return}downloadText(JSON.stringify(lastBenchmark,null,2),`forklift_benchmark_${lastBenchmark.seed}.json`,'application/json');log('success','Benchmark JSON exported')}
function exportBenchmarkCsv(){if(!lastBenchmark){log('error','No benchmark result');return}const cols=['controller','trials','successRate','collisionRate','avgPathLength','avgSimTimeSec','avgControlTicks','avgCTE','avgFailures','avgRecoveries'];const csv=[cols.join(','),...lastBenchmark.summary.map(r=>cols.map(c=>r[c]??'').join(','))].join('\n');downloadText(csv,`forklift_benchmark_${lastBenchmark.seed}.csv`,'text/csv');log('success','Benchmark CSV exported')}
function setFailure(path,value,label){if(path==='obstacle')store.state.obstacle.enabled=value;else store.state.failures[path]=value;store.emit();log('planner',`${label}: ${value?'ON':'OFF'}`)}
function downloadEpisode(){const data=episodes.exportLatest();if(!data){log('error','No episode to export');return;}downloadText(data,`forklift_episode_${Date.now()}.json`,'application/json');log('success','Episode JSON exported')}
$('#planBtn').onclick=makePlan;$('#stepBtn').onclick=step;$('#runBtn').onclick=run;$('#batchBtn').onclick=runBatch;$('#benchmarkJsonBtn').onclick=exportBenchmarkJson;$('#benchmarkCsvBtn').onclick=exportBenchmarkCsv;$('#resetBtn').onclick=()=>{running=false;if(episodes.current)episodes.finish(false,'reset');store.reset();renderMetrics();log('planner','System reset')};$('#clearLogBtn').onclick=()=>$('#log').innerHTML='';$('#downloadEpisodeBtn').onclick=downloadEpisode;$('#controllerSelect').onchange=e=>{store.state.simulation.controller=e.target.value;store.emit();log('planner',`Controller → ${e.target.value}`)};$('#lookaheadInput').onchange=e=>{store.state.simulation.lookaheadDistance=Math.max(20,Math.min(120,Number(e.target.value)||55));store.emit();log('planner',`Lookahead → ${store.state.simulation.lookaheadDistance}`)};$('#obstacleToggle').onchange=e=>setFailure('obstacle',e.target.checked,'Obstacle');$('#detectFailToggle').onchange=e=>setFailure('forceDetectionFailure',e.target.checked,'Detection failure');$('#alignFailToggle').onchange=e=>setFailure('forceAlignmentFailure',e.target.checked,'Alignment failure');$('#insertFailToggle').onchange=e=>setFailure('forceInsertionFailure',e.target.checked,'Insertion failure');document.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>{const a=b.dataset.manual;if(a==='forward')robot.sendAction({type:'drive',speed:60,steeringAngle:0});if(a==='back')robot.sendAction({type:'drive',speed:-45,steeringAngle:0});if(a==='left')robot.sendAction({type:'drive',speed:35,steeringAngle:25});if(a==='right')robot.sendAction({type:'drive',speed:35,steeringAngle:-25});if(a==='lift')robot.sendAction({type:'fork',raised:!store.state.robot.forkRaised})});log('planner','Ready: v1.5 seeded multi-scenario Benchmark Suite');
