import {Store} from './src/state/store.js';
import {SimRobot} from './src/robot/sim_robot.js';
import {WarehouseRenderer} from './src/environment/warehouse.js';
import {RulePlanner} from './src/planner/rule_planner.js';
import {Planner} from './src/planner/planner.js';
import {SkillExecutor} from './src/skills/skills.js';
const $=s=>document.querySelector(s);const store=new Store();const robot=new SimRobot(store);robot.connect();const renderer=new WarehouseRenderer($('#simCanvas'));const planner=new Planner(new RulePlanner());const executor=new SkillExecutor(store,robot);let running=false;
function log(type,msg){const d=document.createElement('div');d.className=`log-line ${type}`;const t=new Date().toLocaleTimeString();d.innerHTML=`<span class="time">${t}</span> ${msg}`;$('#log').appendChild(d);$('#log').scrollTop=$('#log').scrollHeight}
function render(s){renderer.draw(s);$('#robotState').textContent=JSON.stringify(s.robot,null,2);$('#agentState').textContent=JSON.stringify({task:s.task,agent:s.agent},null,2);renderQueue(s)}function renderQueue(s){const q=$('#skillQueue');q.innerHTML='';s.agent.queue.forEach((sk,i)=>{const e=document.createElement('div');e.className='skill-item '+(i<s.agent.cursor?'done':i===s.agent.cursor?'current':'');e.innerHTML=`<span>${i+1}. ${sk.name}</span><code>${JSON.stringify(sk.args)}</code>`;q.appendChild(e)})}store.subscribe(render);
async function makePlan(){const text=$('#taskInput').value;const p=await planner.plan(text,store.state);store.state.task=p.task;store.state.agent.queue=p.skills;store.state.agent.cursor=0;store.state.agent.currentSkill=null;store.state.agent.lastResult=null;store.state.agent.status='planned';store.emit();log('planner',`Planner → ${p.skills.length} skills planned for "${text}"`)}
async function step(){const a=store.state.agent;if(a.cursor>=a.queue.length){a.status='done';store.state.task.status='done';store.emit();log('success','Task complete');return false}const sk=a.queue[a.cursor];a.currentSkill=sk.name;a.status='running';store.emit();log('skill',`Skill → ${sk.name} ${JSON.stringify(sk.args)}`);const result=await executor.execute(sk);a.lastResult=result;if(result.ok){log('success',`Result → success: ${result.message||''}`);a.cursor++;if(a.cursor>=a.queue.length){a.status='done';store.state.task.status='done';log('success','Task complete')}}else{a.status='failed';store.state.task.status='failed';log('error',`Result → failed: ${result.reason}`)}store.emit();return result.ok&&a.status!=='done'}
async function run(){if(running)return;running=true;while(running){const keep=await step();if(!keep)break;await new Promise(r=>setTimeout(r,450))}running=false}
$('#planBtn').onclick=makePlan;$('#stepBtn').onclick=step;$('#runBtn').onclick=run;$('#resetBtn').onclick=()=>{running=false;store.reset();log('planner','System reset')};$('#clearLogBtn').onclick=()=>$('#log').innerHTML='';document.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>{const a=b.dataset.manual;if(a==='forward')robot.sendAction({type:'move',dx:0,dy:-18});if(a==='back')robot.sendAction({type:'move',dx:0,dy:18});if(a==='left')robot.sendAction({type:'move',dx:-18,dy:0});if(a==='right')robot.sendAction({type:'move',dx:18,dy:0});if(a==='lift')robot.sendAction({type:'fork',raised:!store.state.robot.forkRaised})});log('planner','Ready: Rule Planner / SimRobot / Rule-based Skills');
